# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
linters:
  enable:
    - revive
    - nilerr
    - gosec
    - gochecksumtype
    - exhaustruct
    - exhaustive
    - paralleltest

severity:
  default-severity: warning
  rules:
    - linters:
        - exhaustruct
      severity: info
